[install]
is_configured = 0

[ui]
is_visible = 0
label = HDF Add-on for Splunk

[launcher]
author = MITRE SAF
description = CIM normalization (Vulnerabilities data model) for HDF (Heimdall Data Format) assessment results produced by `hdf convert --to splunk`.
version = 0.1.0
