package nist

import (
	_ "embed"
	"encoding/json"
	"regexp"
	"strings"
	"sync"
)

// The description tables are generated by scripts/generate-nist-descriptions.mjs
// (Rev 5) and imported by the TypeScript loader, so both languages read one copy.
var (
	//go:embed nist-descriptions.json
	descriptionsRev4 []byte
	//go:embed nist-descriptions-rev5.json
	descriptionsRev5 []byte
)

// Family, control number, then any run of enhancement numbers or statement
// letters, each written as " 3", "(3)" or " (3)", in any letter case. Keep identical to the TypeScript pattern.
var (
	nistIDPattern = regexp.MustCompile(`^([A-Za-z]{2})-(\d{1,2})((?: ?\((?:\d{1,2}|[A-Za-z])\)| (?:\d{1,2}|[A-Za-z]))*)$`)
	nistIDToken   = regexp.MustCompile(`\d+|[A-Za-z]`)
)

var (
	descriptionIDs     map[int]map[string]struct{}
	descriptionIDsOnce sync.Once
)

// NormalizeID normalizes a NIST SP 800-53 identifier such as "AC-2", "AC-2(3)",
// "AC-2 (3)", "AC-02 03", "AC-1 a 1" or "ac-2" to the description-table spelling:
// uppercase family, lowercase statement letters, zero-padded numbers and
// space-separated parts ("AC-02 03"). It reports false when the input is not a
// NIST identifier spelling. A true result is not proof NIST defines the
// control; use NistExistsForRevision for that.
func NormalizeID(id string) (string, bool) {
	m := nistIDPattern.FindStringSubmatch(id)
	if m == nil {
		return "", false
	}
	parts := []string{strings.ToUpper(m[1]) + "-" + padNumber(m[2])}
	for _, token := range nistIDToken.FindAllString(m[3], -1) {
		parts = append(parts, padNumber(strings.ToLower(token)))
	}
	return strings.Join(parts, " "), true
}

func padNumber(token string) string {
	if len(token) == 1 && token[0] >= '0' && token[0] <= '9' {
		return "0" + token
	}
	return token
}

// NistExists reports whether NIST defines id at the process-global revision.
func NistExists(id string) bool {
	return NistExistsForRevision(id, Revision())
}

// NistExistsForRevision reports whether NIST defines id, in any spelling
// NormalizeID accepts, at the given revision. An unsupported revision is
// checked against the default revision's data, as the TypeScript nistExists does.
func NistExistsForRevision(id string, rev int) bool {
	key, ok := NormalizeID(id)
	if !ok {
		return false
	}
	_, found := descriptionIDsFor(rev)[key]
	return found
}

func descriptionIDsFor(rev int) map[string]struct{} {
	descriptionIDsOnce.Do(func() {
		descriptionIDs = make(map[int]map[string]struct{})
		for r, raw := range map[int][]byte{4: descriptionsRev4, 5: descriptionsRev5} {
			if ids, err := parseDescriptionIDs(raw); err == nil {
				descriptionIDs[r] = ids
			}
		}
	})
	if ids, ok := descriptionIDs[rev]; ok {
		return ids
	}
	return descriptionIDs[DefaultRevision]
}

func parseDescriptionIDs(raw []byte) (map[string]struct{}, error) {
	var descriptions map[string]string
	if err := json.Unmarshal(raw, &descriptions); err != nil {
		return nil, err
	}
	ids := make(map[string]struct{}, len(descriptions))
	for id := range descriptions {
		ids[id] = struct{}{}
	}
	return ids, nil
}
