import { mkdirSync, existsSync, writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import {
  quicktype,
  InputData,
  JSONSchemaInput,
  FetchingJSONSchemaStore,
} from 'quicktype-core';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const DIST_SCHEMAS_DIR = join(__dirname, '..', 'dist', 'schemas');
const DIST_DIR = join(__dirname, '..', 'dist');

// Schemas to generate types for
const SCHEMAS = [
  { file: 'hdf-results.schema.json', name: 'HdfResults' },
  { file: 'hdf-baseline.schema.json', name: 'HdfBaseline' },
  { file: 'hdf-comparison.schema.json', name: 'HdfComparison' },
];

// Language configurations
const LANGUAGES = [
  { name: 'typescript', dir: 'ts', ext: 'ts', options: { 'just-types': true } },
  { name: 'go', dir: 'go', ext: 'go', options: { package: 'hdf' } },
  { name: 'python', dir: 'python', ext: 'py', options: { 'python-version': '3.7' } },
];

/**
 * Convert a schema filename to output filename for a given language.
 */
function toOutputFilename(schemaFile: string, ext: string): string {
  // hdf-results.schema.json -> hdf-results.ts or hdf_results.go
  const base = schemaFile.replace('.schema.json', '');
  if (ext === 'go' || ext === 'py') {
    return base.replace(/-/g, '_') + '.' + ext;
  }
  return base + '.' + ext;
}

/**
 * Generate types for a single schema in a single language.
 */
async function generateForLanguage(
  schemaPath: string,
  typeName: string,
  language: string,
  options: Record<string, unknown>
): Promise<string> {
  const schemaContent = readFileSync(schemaPath, 'utf-8');

  const schemaInput = new JSONSchemaInput(new FetchingJSONSchemaStore());
  await schemaInput.addSource({ name: typeName, schema: schemaContent });

  const inputData = new InputData();
  inputData.addInput(schemaInput);

  const result = await quicktype({
    inputData,
    lang: language as 'typescript' | 'go' | 'python',
    rendererOptions: options as Record<string, string>,
  });

  return result.lines.join('\n');
}

/**
 * Generate types for multiple schemas combined into a single file.
 * Used for Go to avoid duplicate type declarations.
 */
async function generateCombinedForLanguage(
  schemas: Array<{ path: string; name: string }>,
  language: string,
  options: Record<string, unknown>
): Promise<string> {
  const schemaInput = new JSONSchemaInput(new FetchingJSONSchemaStore());

  for (const schema of schemas) {
    const schemaContent = readFileSync(schema.path, 'utf-8');
    await schemaInput.addSource({ name: schema.name, schema: schemaContent });
  }

  const inputData = new InputData();
  inputData.addInput(schemaInput);

  const result = await quicktype({
    inputData,
    lang: language as 'typescript' | 'go' | 'python',
    rendererOptions: options as Record<string, string>,
  });

  return result.lines.join('\n');
}

/**
 * Add omitempty tags to optional pointer fields in generated Go code.
 * This ensures that nil/null fields are omitted from JSON output, matching
 * the discriminated union semantics of the schema.
 */
function addOmitemptyToGoCode(code: string): string {
  // Pattern matches Go struct fields with pointer types and json tags
  // Example: FQDN *string `json:"fqdn"`
  // Captures: field name, type, json tag name, and closing backtick
  const fieldPattern = /(\w+)\s+(\*\w+(?:<[^>]+>)?|\*time\.Time)\s+`json:"([^"]+)"`/g;

  return code.replace(fieldPattern, (match, fieldName, fieldType, jsonTag) => {
    // Only add omitempty if not already present
    if (jsonTag.includes('omitempty')) {
      return match;
    }

    // Add omitempty to the json tag
    const newJsonTag = `${jsonTag},omitempty`;
    return `${fieldName} ${fieldType} \`json:"${newJsonTag}"\``;
  });
}

/**
 * Generate go.mod file for the Go types package.
 */
function generateGoMod(outputDir: string): void {
  const goModContent = `// Code generated by hdf-schema build. DO NOT EDIT.
module github.com/mitre/hdf-schema

go 1.23
`;
  const goModPath = join(outputDir, 'go.mod');
  writeFileSync(goModPath, goModContent);
  console.log(`  → ${goModPath}`);
}

/**
 * Generate types for all schemas in all languages.
 */
export async function generateTypes(): Promise<void> {
  // Ensure bundled schemas exist
  if (!existsSync(DIST_SCHEMAS_DIR)) {
    throw new Error(
      'Bundled schemas not found. Run `pnpm build:schemas` first.'
    );
  }

  for (const lang of LANGUAGES) {
    const outputDir = join(DIST_DIR, lang.dir);

    // Create output directory
    if (!existsSync(outputDir)) {
      mkdirSync(outputDir, { recursive: true });
    }

    console.log(`Generating ${lang.name} types...`);

    // For Go, combine all schemas into a single file to avoid duplicate types
    if (lang.name === 'go') {
      const schemasToGenerate: Array<{ path: string; name: string }> = [];

      for (const schema of SCHEMAS) {
        const schemaPath = join(DIST_SCHEMAS_DIR, schema.file);
        if (!existsSync(schemaPath)) {
          console.warn(`  Skipping ${schema.file} (not found)`);
          continue;
        }
        schemasToGenerate.push({ path: schemaPath, name: schema.name });
      }

      if (schemasToGenerate.length > 0) {
        let code = await generateCombinedForLanguage(
          schemasToGenerate,
          lang.name,
          lang.options
        );

        // Add omitempty tags to optional fields for discriminated union support
        code = addOmitemptyToGoCode(code);

        const outputPath = join(outputDir, 'hdf.go');
        writeFileSync(outputPath, code);
        console.log(`  → ${outputPath}`);
      }

      generateGoMod(outputDir);
      continue;
    }

    // For other languages, generate separate files per schema
    for (const schema of SCHEMAS) {
      const schemaPath = join(DIST_SCHEMAS_DIR, schema.file);
      const outputFile = toOutputFilename(schema.file, lang.ext);
      const outputPath = join(outputDir, outputFile);

      if (!existsSync(schemaPath)) {
        console.warn(`  Skipping ${schema.file} (not found)`);
        continue;
      }

      const code = await generateForLanguage(
        schemaPath,
        schema.name,
        lang.name,
        lang.options
      );

      writeFileSync(outputPath, code);
      console.log(`  → ${outputPath}`);
    }
  }

  console.log('Done.');
}

// Run if called directly
/* c8 ignore start */
if (import.meta.url === `file://${process.argv[1]}`) {
  generateTypes().catch((err) => {
    console.error('Type generation failed:', err);
    process.exit(1);
  });
}
/* c8 ignore stop */
