import { mkdirSync, existsSync, writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath, pathToFileURL } from 'url';
import {
  quicktype,
  InputData,
  JSONSchemaInput,
  FetchingJSONSchemaStore,
} from 'quicktype-core';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const DIST_SCHEMAS_DIR = join(__dirname, '..', 'dist', 'schemas');
const DIST_DIR = join(__dirname, '..', 'dist');

// Schemas to generate types for.
// Names use HDF (uppercase acronym) matching schema title fields ("HDF Results", etc.).
// This ensures combined quicktype output produces correct root type names.
const SCHEMAS = [
  { file: 'hdf-results.schema.json', name: 'HDFResults' },
  { file: 'hdf-baseline.schema.json', name: 'HDFBaseline' },
  { file: 'hdf-comparison.schema.json', name: 'HDFComparison' },
  { file: 'hdf-system.schema.json', name: 'HDFSystem' },
  { file: 'hdf-plan.schema.json', name: 'HDFPlan' },
  { file: 'hdf-amendments.schema.json', name: 'HDFAmendments' },
  { file: 'hdf-evidence-package.schema.json', name: 'HDFEvidencePackage' },
];

const LANGUAGES = [
  { name: 'typescript', dir: 'ts', options: { 'just-types': 'true' } },
  { name: 'go', dir: 'go', options: { 'package': 'hdf', 'omit-empty': 'true' } },
];

/**
 * Preprocess a JSON Schema to work around quicktype-core 23.x bugs:
 * 1. Replace bare primitive types in oneOf with a wrapper object so quicktype
 *    can generate a name for the variant (avoids codePointAt crash).
 * 2. Remove `const: true` boolean properties (quicktype can't handle const).
 */
function preprocessSchemaForQuicktype(schemaJson: string): string {
  const schema = JSON.parse(schemaJson);

  function walk(node: unknown): unknown {
    if (node === null || typeof node !== 'object') return node;
    if (Array.isArray(node)) return node.map(walk);

    const obj = node as Record<string, unknown>;

    if (obj['type'] === 'boolean' && 'const' in obj) {
      const { const: _, ...rest } = obj;
      void _;
      return walk(rest);
    }

    if (Array.isArray(obj['oneOf'])) {
      const items = obj['oneOf'] as Array<Record<string, unknown>>;
      const hasBare = items.some(
        (i) => typeof i['type'] === 'string' && !i['$ref']
      );
      const hasRef = items.some((i) => '$ref' in i);
      if (hasBare && hasRef) {
        const { oneOf: __, ...rest } = obj;
        void __;
        return walk({ ...rest, description: obj['description'] });
      }
    }

    const result: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = walk(value);
    }
    return result;
  }

  return JSON.stringify(walk(schema));
}

/**
 * Generate go.mod file for the Go types package.
 */
function generateGoMod(outputDir: string): void {
  const goModContent = `// Code generated by hdf-schema build. DO NOT EDIT.
module github.com/mitre/hdf-libs/hdf-schema/dist/go/v3

go 1.26
`;
  writeFileSync(join(outputDir, 'go.mod'), goModContent);
}

/**
 * Generate types for all schemas in all languages (combined output).
 */
export async function generateTypes(): Promise<void> {
  if (!existsSync(DIST_SCHEMAS_DIR)) {
    throw new Error(
      'Bundled schemas not found. Run `pnpm build:schemas` first.'
    );
  }

  // Collect schemas once — same set for all languages
  const schemasToGenerate: Array<{ path: string; name: string }> = [];
  for (const schema of SCHEMAS) {
    const schemaPath = join(DIST_SCHEMAS_DIR, schema.file);
    if (!existsSync(schemaPath)) {
      console.warn(`  Skipping ${schema.file} (not found)`);
      continue;
    }
    schemasToGenerate.push({ path: schemaPath, name: schema.name });
  }

  if (schemasToGenerate.length === 0) {
    throw new Error('No schemas found in dist/schemas/');
  }

  // Preprocess each schema once (output is deterministic), then build a fresh
  // JSONSchemaInput per language inside Promise.all — quicktype mutates its
  // input's internal state, so the two languages cannot share one input.
  const preprocessed = schemasToGenerate.map((schema) => ({
    name: schema.name,
    schema: preprocessSchemaForQuicktype(readFileSync(schema.path, 'utf-8')),
  }));

  await Promise.all(LANGUAGES.map(async (lang) => {
    const outputDir = join(DIST_DIR, lang.dir);
    if (!existsSync(outputDir)) {
      mkdirSync(outputDir, { recursive: true });
    }

    console.log(`Generating ${lang.name} types...`);

    const langSchemaInput = new JSONSchemaInput(new FetchingJSONSchemaStore());
    for (const entry of preprocessed) {
      await langSchemaInput.addSource(entry);
    }

    const inputData = new InputData();
    inputData.addInput(langSchemaInput);

    const result = await quicktype({
      inputData,
      lang: lang.name as 'typescript' | 'go',
      rendererOptions: lang.options,
    });

    const ext = lang.name === 'go' ? 'go' : 'ts';
    const outputPath = join(outputDir, `hdf.${ext}`);
    writeFileSync(outputPath, result.lines.join('\n'));
    console.log(`  → ${outputPath}`);

    if (lang.name === 'go') {
      generateGoMod(outputDir);
    }
  }));

  console.log('Done.');
}

// Run if called directly
/* c8 ignore start */
if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  generateTypes().catch((err) => {
    console.error('Type generation failed:', err);
    process.exit(1);
  });
}
/* c8 ignore stop */
